on:
  pull_request:
  push:
    branches: [main, beta]
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix flake check --show-trace
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: check
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: cihelper/action-semanticrelease-npm@v1
        id: semanticrelease
      - run: nix run .#dockerManifest --impure
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
        env:
          VERSION: ${{ steps.semanticrelease.outputs.version }}
          GH_TOKEN: ${{ github.token }}
